### ISSUE TITLE
Assignment 2 Grading

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/Architects#100]
Hi Team,
Can you mail the credentials for the Jenkins server:
Email: rtalwai@iu.edu

**Comment by deepakh2810** [comment]
Hi Raghottam,

I have mailed the credentials to the given email I’d. Hence, closing the issue.

Best,
Deepak Hanumanthaiah

**Comment by raghu2094** [comment]
Hi Team,
I ran all your build jobs. All the builds were successful. 
Now I am trying to register in the application but getting an Invalid data error. Not sure which field is invalid. Please see the attached image
![image](https://user-images.githubusercontent.com/31967000/54794392-96d7d300-4c1d-11e9-9321-1c54452e19e5.png)

**Comment by AdithyaHS** [comment]
Hello Raghottam,

I will check it right away.

Thanks & Regards,
Adithya HS

**Comment by AdithyaHS** [comment]
Hello Raghottam,

Thanks for noticing. The reason that register was not working was that we
had our testing instance of user-management service registered with the
zookeeper instead of the actual one. I shut down that instance and made
sure that the correct instance is registered. You can carry out your
testing now.

Thanks & Regards,
Adithya HS

**Comment by raghu2094** [comment]
Hey Team,
Good job with Assignment 2.
W.r.t CI/CD , in WIKI you have mentioned 

"Each job includes steps to get the latest code from git, generate a docker image and run the container using the latest Docker image, and deploy to the remote instance where containers consisting of the micro-service runs"
After going through your Jenkins configurations, I noticed that your are creating the docker image and running it on the remote instance itself i.e your slave node and also that you haven't included tests for each service. 
Imagine a scenario wherein you commit some changes that induce bug in your service, what will happen if you directly build and run the container without testing the new changes ?
Ideally , Building and testing should be done on a separate instance so that even if the tests fail, the existing running process inside the container wouldn't be killed.

Service discovery with zookeeper has been well executed.
Great job with the documentation, Each section is well explained. 

Regards,
Raghottam

**Comment by deepakh2810** [comment]
Hi Raghu,

I have closing the issue after implementing test cases pre deployment.
Commit ID: 98c6b0642fc0e9b6c697b633827ba18a7680ab74.
