### ISSUE TITLE
Peer Review Milestone 3

### ISSUE THREAD

**Issue by psethu** [airavata-courses/Architects#101]

**Comment by psethu** [comment]
Hi, just checking, is the site temporarily down? I am unable to access application here:
http://149.165.170.200:3000/

**Comment by psethu** [comment]
At this time site is live. Thanks!

**Comment by psethu** [comment]
I have tested site using JMeter to verify performance. Application can handle 100 to even 1000 users at once that repeatedly, for few times, want to connect to application. There are few instances of 10 second delay but in true situation, the problem is considered only if time reaches minutes. Good job on this!

**Comment by deepakh2810** [comment]
Thank you Sethu!
We wil work towards handling this better next time.
