### ISSUE TITLE
Update Wiki and Login Credentials 

### ISSUE THREAD

**Issue by prathameshd** [airavata-courses/Architects#106]
Hi Team,

Can you update the wiki and also give me login credentials for Jenkins dashboard and Kubernetes dashboard.

Thanks,
Prathamesh

**Comment by prathameshd** [comment]
Team,

The architecture diagram for Milestone 3 has not been updated. Can you update the same?

**Comment by deepakh2810** [comment]
Updated. Hence, closing the issue
