### ISSUE TITLE
Invalid Data Error while Signup 

### ISSUE THREAD

**Issue by prathameshd** [airavata-courses/Architects#107]
Team,
I am getting invalid data error when i am trying to create a new account.

**Comment by harishmaruthi** [comment]
Please try now.
It should be working. 

The backend service was down.

**Comment by prathameshd** [comment]
Account was created but unable to login. Getting invalid credentials error
Can you check?

**Comment by deepakh2810** [comment]
Hi Prathamesh,

The feature seems to be working just fine.
Please check and re open the issue if it exists.
