### ISSUE TITLE
Google Login not working

### ISSUE THREAD

**Issue by absheth** [airavata-courses/Architects#114]
I tried to test the Google Login but I am getting the below error. 

<img width="642" alt="Screen Shot 2019-04-24 at 22 20 29" src="https://user-images.githubusercontent.com/14033748/56705538-51586b00-66df-11e9-8f5a-e04804cc077f.png">

**Comment by prathameshd** [comment]
Team,
I am facing the same issue.

**Comment by harishmaruthi** [comment]
Hi @prathameshd, @absheth,
Thank you. Please do verify at: http://js-171-205.jetstream-cloud.org:30008/ deployment version with right commit head.

Thanks,

Harish.
