### ISSUE TITLE
Register fails to redirect

### ISSUE THREAD

**Issue by Chirag-Galani** [airavata-courses/Architects#49]
The Registration process is successful but the user doesn't get a confirmation for that and is not redirected to the login screen

**Comment by ATarfe** [comment]
I agree, the app fails to redirect after the completion of the registration. Also, there is no feedback after the registration.

**Comment by AdithyaHS** [comment]
Than you for providing feedback. The above mentioned commits take cares care of this issue. please review the same.

**Comment by Chirag-Galani** [comment]
Issue fixed. Good Job
