### ISSUE TITLE
Unable to add a new project

### ISSUE THREAD

**Issue by Chirag-Galani** [airavata-courses/Architects#50]
The user cannot insert a new project, an error pops up stating 'Error Inserting Data' but immediately redirects to the main page without adding the project in the project table

**Comment by harishmaruthi** [comment]
Issue Fixed. Pull latest Development, review and close.

**Comment by Chirag-Galani** [comment]
I pulled the latest code and still face the issue.
Also, can you show in the Error atleast where exactly it needs to be fixed (number instead of string)

**Comment by Chirag-Galani** [comment]
<img width="946" alt="screen shot 2019-02-10 at 8 10 23 pm" src="https://user-images.githubusercontent.com/4441071/52542649-0a113e00-2d70-11e9-84db-add8e8d5d051.png">

**Comment by Chirag-Galani** [comment]
Also, can you show in the Error at least where exactly the data needs to be corrected

**Comment by Chirag-Galani** [comment]
Issue fixed. Error on my part: Forgot to run the steps for the project module microservice
