### ISSUE TITLE
Peer review Assignment 1

### ISSUE THREAD

**Issue by ATarfe** [airavata-courses/Architects#51]
Minor issues with 9TO5IT:

1. Register redirect: The app fails to redirect after the completion of the registration. Also, there is no 
                                feedback after the registration.

2. Login button: The page shows login even after logging in.

3.  Adding project : The adding project functionality is not working properly.

Kindly review the issues, Thank you.

**Comment by harishmaruthi** [comment]
Issue Fixed. Pull latest Development, review and close.
