### ISSUE TITLE
Peer Review Assignment 1

### ISSUE THREAD

**Issue by vrishalibhor** [airavata-courses/Architects#55]
Hello Team,

The wiki is very well documented and that makes the application really easy to install and run :)

However, these are some issues that I observed:

1. User Registration is not working #56
2. Unable to add new projects #50
3. GUI enhancements: 
	a) Redirect user to login page after registration is complete or show appropriate error #49
	b) Redirect user to home page after login is successful or show appropriate error #48
	c) Give the user an appropriate message upon adding a new Project #50

Since these issues are already raised (except for the first one), I'm not raising them again.

**Comment by harishmaruthi** [comment]
Issue Fixed. Pull latest Development, review and close.

**Comment by vrishalibhor** [comment]
Hello,

The above issues are resolved.
However, I have two suggestions (Enhancements) :
1. It would be great if there is a separate link for Registration. The user need not go to Login for that.
2. During registration, the user should be notified in which field has he entered invalid data. Right now, a user has to go through each field to check what is invalid.

**Comment by deepakh2810** [comment]
Thanks for the feedback vrishali, we will work towards this.
