### ISSUE TITLE
Auto logged in on launch

### ISSUE THREAD

**Issue by Chirag-Galani** [airavata-courses/Architects#67]
On deploying I noticed that the app was auto-logged in. I had to click on logout to get the login screen and enter the credentials

**Comment by harishmaruthi** [comment]
This needs design change at client side auth!

**Comment by harishmaruthi** [comment]
Hey Chirag, Thanks for your observation.

_### Issue discussion:_

**As designed.**
While using the application user should not feel any difference as a result of the backend server state changes. User should seamlessly be using the application even if the server gets down and a new version is deployed.
I hope this isn't a bug. 

**Please reopen if our understanding is wrong about the issue**
