### ISSUE TITLE
Logout UI bug

### ISSUE THREAD

**Issue by Chirag-Galani** [airavata-courses/Architects#68]
Once the user clicks logout, the app logs out successfully, but it still shows the Logout button on the top right (which contradicts the logout message 'Thank you for using 9to5It'). When I reclick Logout button it changes to Login (which is the expected behaviour)

**Comment by Chirag-Galani** [comment]
<img width="1304" alt="screen shot 2019-02-10 at 8 14 19 pm" src="https://user-images.githubusercontent.com/4441071/52542700-8e63c100-2d70-11e9-984b-7bb9e4eb90e3.png">

**Comment by harishmaruthi** [comment]
Remove user session token on click of logout button. Earlier used happen on Logout component load.

Good find, Chirag. 
Thanks.
