### ISSUE TITLE
Difference between Organization and Freelancers 

### ISSUE THREAD

**Issue by Chirag-Galani** [airavata-courses/Architects#70]
I registered as a freelancer as well as an organization but couldn't figure out the difference between them as all the entries are added to freelancers section

**Comment by harishmaruthi** [comment]
Looks like we may need to 2 columns to list 2 types of users separately.

**Comment by deepakh2810** [comment]
The UI has been differentiated. There has been a different view for a free lancer and an Organization.
Thank you for the feedback.
