### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Architects#74]
Hey team,

I just started with the code review. Will update my progress/issues here.

Thanks,
Nawaz

**Comment by nawazkh** [comment]
Hey Team,

I am unable to log into the system.
I created a new user Id and password, and here is the error. 
<img width="723" alt="screen shot 2019-02-20 at 3 28 26 pm" src="https://user-images.githubusercontent.com/25679594/53122275-32ddc400-3524-11e9-8c8b-d2c92e6de8da.png">

Please share a login credential which I can use for login and test other functionalities.

-nawaz

**Comment by deepakh2810** [comment]
Hi Nawaz,

Username: dhanuman@iu.edu
Password: hi1234

**Comment by nawazkh** [comment]
Hey Team,

Great work!
It is really good to see that all the Microservices are working well and the site is up and running!

I have a few suggestions coming to the project.
1. This appears to be a create-and-view website. Can you add more functionality to it? For example, managing user profile, where a user can see the projects they are working on.
2. Some functionality can be added to the organizer Or the person creating the projects as well. Do look into it, any more functionality will have a great learning experience in the project.
3. Importantly, please update the Napkin diagram of your project highlighting each service being offered in your system.

Please close this issue once you have viewed it.
Keep up the good work! 

Regards,
Nawaz

**Comment by deepakh2810** [comment]
Thank you for the Feedback Nawaz!
Will look into addition of more Functionality.
