### ISSUE TITLE
Peer Review Milestone 2

### ISSUE THREAD

**Issue by iarora93** [airavata-courses/Architects#89]

**Comment by iarora93** [comment]
Could you please share Jenkins Username and password 
Email address is iarora@iu.edu

**Comment by harishmaruthi** [comment]
shared personally. Cannot be added here...

**Comment by iarora93** [comment]
I am reopening this issue.
It is going to be used for the issues faced as well as for suggestions

**Comment by harishmaruthi** [comment]
Okay, that's good. You can do that

**Comment by iarora93** [comment]
1)When registering for the first time, if an email is already used previously it is displaying that invalid character instead of email already used.
2)Not able to add a project.Getting error invalid data entered.
3)CI/CD seems to be working fine.
4)Suggestion-Could have created Deployment Scripts for the same.
5)Suggestion-Seems User Details button is not linked properly

**Comment by AdithyaHS** [comment]
Hello @iarora93 ,

Thanks for letting us know about the issues and we would definitely consider your suggestions for the next deadline. Here I am letting you know that we have traced the 2nd issue to its source and have found out that our api-gateway was not able to route the request to the correct path under specific circumstances. We have addressed this issue in the above check-ins. Could you please verify the same and let us know the result?

**Comment by AdithyaHS** [comment]
closing this issue
