### ISSUE TITLE
Bad request on Add Project form

### ISSUE THREAD

**Issue by bhushanmalgaonkar** [airavata-courses/Architects#93]
I'm getting bad request on add project form even when I'm entering proper values (according to placeholders). There might be some conditions you are using to validate my input but I'm not getting feedback of what field value is wrong. 

It'd be helpful if you could provide appropriate errors.

**Comment by AdithyaHS** [comment]
Hello @bhushanmalgaonkar ,

Thanks for letting us know about this issue. We have traced the issue to its source and have found out that our api-gateway was not able to route the request to the correct path under specific circumstances. We have addressed this issue in the above check-ins. Could you please verify the same and let us know the result?

**Comment by bhushanmalgaonkar** [comment]
Add project is working correctly now!

**Comment by AdithyaHS** [comment]
@bhushanmalgaonkar ,

 Thanks for closing the issue.

Regards,
Adithya HS
