### ISSUE TITLE
Peer review milestone 2

### ISSUE THREAD

**Issue by bhushanmalgaonkar** [airavata-courses/Architects#98]
Hi, 

Very clean implementation of CI/CD. Each microservice has its dedicated job on Jenkins and pipeline to execute then sequentially with one click.

The project seems to work fine. Although, I Observed one issue apart from what others have already raised.
1. Bad request on add project form #93. It'd be helpful if we get to see the errors for invalid form entries. 

As a suggestion, I think, UI can be improved. Specifically, you could have separate sections for freelancers and organizations.

**Comment by AdithyaHS** [comment]
Hello @bhushanmalgaonkar ,

Thanks for letting us know about the issues. We are currently working on the issues and would keep you updated regarding the same.

Thanks & Regards
Adithya HS

**Comment by AdithyaHS** [comment]
Hello @bhushanmalgaonkar ,

I have mentioned the reason for bad request on ticket #93 .  Thanks for giving us your valuable suggestions we would definitely consider this for the upcoming deadlines. Meanwhile, as i have already mentioned on ticket #93 could you please verify if adding projects is working? 

Again, thanks for your time.
